export const FETCH_SUGGESTIONS = 'SEARCH_BOX/FETCH_SUGGESTIONS';
export const FETCH_SUGGESTIONS_FAILURE = 'SEARCH_BOX/FETCH_SUGGESTIONS_FAILURE';
export const FETCH_SUGGESTIONS_SUCCESS = 'SEARCH_BOX/FETCH_SUGGESTIONS_SUCCESS';

export const SELECT_SUGGESTION = 'SEARCH_BOX/SELECT_SUGGESTION';
export const SELECT_SUGGESTION_FAILURE = 'SEARCH_BOX/SELECT_SUGGESTION_FAILURE';
export const SELECT_SUGGESTION_SUCCESS = 'SEARCH_BOX/SELECT_SUGGESTION_SUCCESS';

export const UPDATE_SEARCH_VALUE = 'SEARCH_BOX/UPDATE_SEARCH_VALUE';
